apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pgbouncer-claim0
  name: pgbouncer-claim0
  namespace: airflow0908
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # Optional: Specify a storage class if required
  # storageClassName: <your-storage-class>
